class ProjectTask {
  String name;
  String project;
  String client;
  String tracker;
  String priority;
  String description;
  String deadlineDate;
  String progress;
  String status;
  List<String> todoList;

  ProjectTask(
      {required this.name,
      required this.project,
      required this.description,
      required this.client,
      required this.deadlineDate,
      required this.tracker,
      required this.priority,
      required this.progress,
      required this.status,
      required this.todoList});
}

var ProjectTaskList = [
  ProjectTask(
      name: 'Backmarket API sync - product',
      project: 'Odoo-Chapp',
      client: 'Chapp',
      description:
      'at first setup we need to pull all  the offers in backmarket into the system. after the initial setup then we will do all the creation, and adjustment from the system. we have to sync all the created and adjusted offers into backmarket in daily basis.',
      tracker: 'Feature',
      priority: 'Low',
      deadlineDate: '01-09-2024',
      progress: '75%',
      status: 'Feedback',
      todoList: ['Pull initial offers',
        'Sync offers daily',
        'Adjust offers in system',
        'Notify on failed sync',
        'Optimize sync speed',
        'Handle product variations',
        'Track adjustments',
        'Test with real data',
        'Create documentation',
        'Get client feedback',
      ],),

  ProjectTask(
      name: 'Sales order container',
      project: 'Designtegels',
      client: 'Martin',
      description:
      'In designtegels they are storing the stock with the container, one PO will be using one container. one container can have multiple products. sasles order will be taking stock from the container instead of the standard warehouse',
      tracker: 'Feature',
      priority: 'Mid',
      deadlineDate: '05-09-2024',
      progress: '100%',
      status: 'Feedback',
      todoList: ['Pull initial offers',
        'Sync offers daily',
        'Adjust offers in system',
        'Notify on failed sync',
        'Optimize sync speed',
        'Handle product variations',
        'Track adjustments',
        'Test with real data',
        'Create documentation',
        'Get client feedback',
      ],),

  ProjectTask(
      name: 'Pebble system upgrade to v17',
      project: 'Pebble',
      client: 'Pebble',
      description:
      'Upgrade the database from v13 to v17. step by step upgrading from v13 > v16 > v17 with all the custom modules',
      tracker: 'Support',
      priority: 'High',
      deadlineDate: '01-01-2024',
      progress: '80%',
      status: 'In Progress',
      todoList: ['Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
        'Sed feugiat dui a finibus sodales.',
        'Sed ac nisi vitae est ultrices sagittis quis et ex.',
        'Sed ut arcu non leo ultrices eleifend.',
        'Suspendisse sit amet mi ac mi consectetur accumsan.',
        'Sed laoreet diam a mauris molestie, a venenatis nisi eleifend',
        'Duis eget orci tincidunt, suscipit nisi nec, varius massa.',
        'Nulla sed risus suscipit, scelerisque ante eget, venenatis lectus.',
        'Pellentesque dignissim lorem non felis pharetra, ultrices facilisis sem faucibus.',
        'Aliquam pharetra erat non condimentum sodales.',
        'Maecenas blandit risus eget leo volutpat, sed interdum felis venenatis.',
        'Phasellus sodales lectus ac elit luctus, a mollis leo dictum.',
        'Praesent at libero eget tortor venenatis posuere ut quis sem.',
        'Donec sed metus molestie, imperdiet libero non, sagittis tellus.',
        'Donec vel sem vel purus cursus fringilla vitae eget leo.'
      ],),

  ProjectTask(
      name: 'Backmarket API sync - product',
      project: 'Odoo-Chapp',
      client: 'Chapp',
      description:
      'at first setup we need to pull all  the offers in backmarket into the system. after the initial setup then we will do all the creation, and adjustment from the system. we have to sync all the created and adjusted offers into backmarket in daily basis.',
      tracker: 'Feature',
      priority: 'Low',
      deadlineDate: '01-09-2024',
      progress: '75%',
      status: 'Feedback',
      todoList: ['Pull initial offers',
        'Sync offers daily',
        'Adjust offers in system',
        'Notify on failed sync',
        'Optimize sync speed',
        'Handle product variations',
        'Track adjustments',
        'Test with real data',
        'Create documentation',
        'Get client feedback',
      ],),

  ProjectTask(
      name: 'Sales order report not the same as v13',
      project: 'Pebble',
      client: 'Pebble',
      description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec vel eros sed nulla sodales eleifend sit amet vel velit. Donec tempor tortor sit amet enim molestie hendrerit. Morbi ipsum ex, aliquet at aliquet vitae, egestas eu libero. Curabitur non mattis justo, sed volutpat lectus. Donec feugiat, ligula egestas aliquet accumsan, libero mauris pulvinar enim, ut commodo tellus lorem non urna. Lorem ipsum dolor sit amet, consectetur adipiscing elit. In hac habitasse platea dictumst. Etiam id sem nec sem ornare aliquam et et elit. In vulputate nisi ac scelerisque mollis. Cras et neque non mi eleifend finibus at a felis. Phasellus vel risus massa. Curabitur quis bibendum leo, eget imperdiet elit. Nam ac ante viverra mi ornare euismod ut sit amet erat. Donec dapibus dui nibh, vel gravida augue euismod eget. Etiam congue ultricies elit, id malesuada sem. Cras sollicitudin convallis dolor, tempor malesuada lectus facilisis non. Maecenas varius ullamcorper cursus. Fusce fermentum tincidunt purus eu egestas. Vivamus blandit posuere mauris, sed rhoncus orci bibendum sed. Fusce pulvinar suscipit libero id sodales. Vestibulum dapibus molestie quam quis consectetur. Ut dapibus, mauris eu maximus mollis, tortor arcu tincidunt est, ut bibendum metus mi id libero. Aliquam placerat eu turpis id hendrerit. Proin congue metus ligula, sed imperdiet nisl fermentum nec.',
      tracker: 'Bug',
      priority: 'Low',
      deadlineDate: '01-09-2024',
      progress: '0%',
      status: 'New',
      todoList: ['Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
        'Sed feugiat dui a finibus sodales.',
        'Sed ac nisi vitae est ultrices sagittis quis et ex.',
        'Sed ut arcu non leo ultrices eleifend.',
        'Suspendisse sit amet mi ac mi consectetur accumsan.',
        'Sed laoreet diam a mauris molestie, a venenatis nisi eleifend',
        'Duis eget orci tincidunt, suscipit nisi nec, varius massa.',
        'Nulla sed risus suscipit, scelerisque ante eget, venenatis lectus.',
        'Pellentesque dignissim lorem non felis pharetra, ultrices facilisis sem faucibus.',
        'Aliquam pharetra erat non condimentum sodales.',
        'Maecenas blandit risus eget leo volutpat, sed interdum felis venenatis.',
        'Phasellus sodales lectus ac elit luctus, a mollis leo dictum.',
        'Praesent at libero eget tortor venenatis posuere ut quis sem.',
        'Donec sed metus molestie, imperdiet libero non, sagittis tellus.',
        'Donec vel sem vel purus cursus fringilla vitae eget leo.'
      ],),

  ProjectTask(
    name: 'Backmarket API sync - product',
    project: 'Odoo-Chapp',
    client: 'Chapp',
    description:
    'at first setup we need to pull all  the offers in backmarket into the system. after the initial setup then we will do all the creation, and adjustment from the system. we have to sync all the created and adjusted offers into backmarket in daily basis.',
    tracker: 'Feature',
    priority: 'Low',
    deadlineDate: '01-09-2024',
    progress: '75%',
    status: 'Feedback',
    todoList: ['Pull initial offers',
      'Sync offers daily',
      'Adjust offers in system',
      'Notify on failed sync',
      'Optimize sync speed',
      'Handle product variations',
      'Track adjustments',
      'Test with real data',
      'Create documentation',
      'Get client feedback',
    ],),

  ProjectTask(
    name: 'Sales order container',
    project: 'Designtegels',
    client: 'Martin',
    description:
    'In designtegels they are storing the stock with the container, one PO will be using one container. one container can have multiple products. sasles order will be taking stock from the container instead of the standard warehouse',
    tracker: 'Feature',
    priority: 'Mid',
    deadlineDate: '05-09-2024',
    progress: '100%',
    status: 'Feedback',
    todoList: ['Pull initial offers',
      'Sync offers daily',
      'Adjust offers in system',
      'Notify on failed sync',
      'Optimize sync speed',
      'Handle product variations',
      'Track adjustments',
      'Test with real data',
      'Create documentation',
      'Get client feedback',
    ],),

  ProjectTask(
    name: 'Pebble system upgrade to v17',
    project: 'Pebble',
    client: 'Pebble',
    description:
    'Upgrade the database from v13 to v17. step by step upgrading from v13 > v16 > v17 with all the custom modules',
    tracker: 'Support',
    priority: 'High',
    deadlineDate: '01-01-2024',
    progress: '80%',
    status: 'In Progress',
    todoList: ['Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      'Sed feugiat dui a finibus sodales.',
      'Sed ac nisi vitae est ultrices sagittis quis et ex.',
      'Sed ut arcu non leo ultrices eleifend.',
      'Suspendisse sit amet mi ac mi consectetur accumsan.',
      'Sed laoreet diam a mauris molestie, a venenatis nisi eleifend',
      'Duis eget orci tincidunt, suscipit nisi nec, varius massa.',
      'Nulla sed risus suscipit, scelerisque ante eget, venenatis lectus.',
      'Pellentesque dignissim lorem non felis pharetra, ultrices facilisis sem faucibus.',
      'Aliquam pharetra erat non condimentum sodales.',
      'Maecenas blandit risus eget leo volutpat, sed interdum felis venenatis.',
      'Phasellus sodales lectus ac elit luctus, a mollis leo dictum.',
      'Praesent at libero eget tortor venenatis posuere ut quis sem.',
      'Donec sed metus molestie, imperdiet libero non, sagittis tellus.',
      'Donec vel sem vel purus cursus fringilla vitae eget leo.'
    ],),

  ProjectTask(
    name: 'Backmarket API sync - product',
    project: 'Odoo-Chapp',
    client: 'Chapp',
    description:
    'at first setup we need to pull all  the offers in backmarket into the system. after the initial setup then we will do all the creation, and adjustment from the system. we have to sync all the created and adjusted offers into backmarket in daily basis.',
    tracker: 'Feature',
    priority: 'Low',
    deadlineDate: '01-09-2024',
    progress: '75%',
    status: 'Feedback',
    todoList: ['Pull initial offers',
      'Sync offers daily',
      'Adjust offers in system',
      'Notify on failed sync',
      'Optimize sync speed',
      'Handle product variations',
      'Track adjustments',
      'Test with real data',
      'Create documentation',
      'Get client feedback',
    ],),

  ProjectTask(
    name: 'Sales order report not the same as v13',
    project: 'Pebble',
    client: 'Pebble',
    description:
    'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec vel eros sed nulla sodales eleifend sit amet vel velit. Donec tempor tortor sit amet enim molestie hendrerit. Morbi ipsum ex, aliquet at aliquet vitae, egestas eu libero. Curabitur non mattis justo, sed volutpat lectus. Donec feugiat, ligula egestas aliquet accumsan, libero mauris pulvinar enim, ut commodo tellus lorem non urna. Lorem ipsum dolor sit amet, consectetur adipiscing elit. In hac habitasse platea dictumst. Etiam id sem nec sem ornare aliquam et et elit. In vulputate nisi ac scelerisque mollis. Cras et neque non mi eleifend finibus at a felis. Phasellus vel risus massa. Curabitur quis bibendum leo, eget imperdiet elit. Nam ac ante viverra mi ornare euismod ut sit amet erat. Donec dapibus dui nibh, vel gravida augue euismod eget. Etiam congue ultricies elit, id malesuada sem. Cras sollicitudin convallis dolor, tempor malesuada lectus facilisis non. Maecenas varius ullamcorper cursus. Fusce fermentum tincidunt purus eu egestas. Vivamus blandit posuere mauris, sed rhoncus orci bibendum sed. Fusce pulvinar suscipit libero id sodales. Vestibulum dapibus molestie quam quis consectetur. Ut dapibus, mauris eu maximus mollis, tortor arcu tincidunt est, ut bibendum metus mi id libero. Aliquam placerat eu turpis id hendrerit. Proin congue metus ligula, sed imperdiet nisl fermentum nec.',
    tracker: 'Bug',
    priority: 'Low',
    deadlineDate: '01-09-2024',
    progress: '0%',
    status: 'New',
    todoList: ['Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      'Sed feugiat dui a finibus sodales.',
      'Sed ac nisi vitae est ultrices sagittis quis et ex.',
      'Sed ut arcu non leo ultrices eleifend.',
      'Suspendisse sit amet mi ac mi consectetur accumsan.',
      'Sed laoreet diam a mauris molestie, a venenatis nisi eleifend',
      'Duis eget orci tincidunt, suscipit nisi nec, varius massa.',
      'Nulla sed risus suscipit, scelerisque ante eget, venenatis lectus.',
      'Pellentesque dignissim lorem non felis pharetra, ultrices facilisis sem faucibus.',
      'Aliquam pharetra erat non condimentum sodales.',
      'Maecenas blandit risus eget leo volutpat, sed interdum felis venenatis.',
      'Phasellus sodales lectus ac elit luctus, a mollis leo dictum.',
      'Praesent at libero eget tortor venenatis posuere ut quis sem.',
      'Donec sed metus molestie, imperdiet libero non, sagittis tellus.',
      'Donec vel sem vel purus cursus fringilla vitae eget leo.'
    ],),
  ProjectTask(
    name: 'Backmarket API sync - product',
    project: 'Odoo-Chapp',
    client: 'Chapp',
    description:
    'at first setup we need to pull all  the offers in backmarket into the system. after the initial setup then we will do all the creation, and adjustment from the system. we have to sync all the created and adjusted offers into backmarket in daily basis.',
    tracker: 'Feature',
    priority: 'Low',
    deadlineDate: '01-09-2024',
    progress: '75%',
    status: 'Feedback',
    todoList: ['Pull initial offers',
      'Sync offers daily',
      'Adjust offers in system',
      'Notify on failed sync',
      'Optimize sync speed',
      'Handle product variations',
      'Track adjustments',
      'Test with real data',
      'Create documentation',
      'Get client feedback',
    ],),

  ProjectTask(
    name: 'Sales order container',
    project: 'Designtegels',
    client: 'Martin',
    description:
    'In designtegels they are storing the stock with the container, one PO will be using one container. one container can have multiple products. sasles order will be taking stock from the container instead of the standard warehouse',
    tracker: 'Feature',
    priority: 'Mid',
    deadlineDate: '05-09-2024',
    progress: '100%',
    status: 'Feedback',
    todoList: ['Pull initial offers',
      'Sync offers daily',
      'Adjust offers in system',
      'Notify on failed sync',
      'Optimize sync speed',
      'Handle product variations',
      'Track adjustments',
      'Test with real data',
      'Create documentation',
      'Get client feedback',
    ],),

  ProjectTask(
    name: 'Pebble system upgrade to v17',
    project: 'Pebble',
    client: 'Pebble',
    description:
    'Upgrade the database from v13 to v17. step by step upgrading from v13 > v16 > v17 with all the custom modules',
    tracker: 'Support',
    priority: 'High',
    deadlineDate: '01-01-2024',
    progress: '80%',
    status: 'In Progress',
    todoList: ['Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      'Sed feugiat dui a finibus sodales.',
      'Sed ac nisi vitae est ultrices sagittis quis et ex.',
      'Sed ut arcu non leo ultrices eleifend.',
      'Suspendisse sit amet mi ac mi consectetur accumsan.',
      'Sed laoreet diam a mauris molestie, a venenatis nisi eleifend',
      'Duis eget orci tincidunt, suscipit nisi nec, varius massa.',
      'Nulla sed risus suscipit, scelerisque ante eget, venenatis lectus.',
      'Pellentesque dignissim lorem non felis pharetra, ultrices facilisis sem faucibus.',
      'Aliquam pharetra erat non condimentum sodales.',
      'Maecenas blandit risus eget leo volutpat, sed interdum felis venenatis.',
      'Phasellus sodales lectus ac elit luctus, a mollis leo dictum.',
      'Praesent at libero eget tortor venenatis posuere ut quis sem.',
      'Donec sed metus molestie, imperdiet libero non, sagittis tellus.',
      'Donec vel sem vel purus cursus fringilla vitae eget leo.'
    ],),

  ProjectTask(
    name: 'Backmarket API sync - product',
    project: 'Odoo-Chapp',
    client: 'Chapp',
    description:
    'at first setup we need to pull all  the offers in backmarket into the system. after the initial setup then we will do all the creation, and adjustment from the system. we have to sync all the created and adjusted offers into backmarket in daily basis.',
    tracker: 'Feature',
    priority: 'Low',
    deadlineDate: '01-09-2024',
    progress: '75%',
    status: 'Feedback',
    todoList: ['Pull initial offers',
      'Sync offers daily',
      'Adjust offers in system',
      'Notify on failed sync',
      'Optimize sync speed',
      'Handle product variations',
      'Track adjustments',
      'Test with real data',
      'Create documentation',
      'Get client feedback',
    ],),

  ProjectTask(
    name: 'Sales order report not the same as v13',
    project: 'Pebble',
    client: 'Pebble',
    description:
    'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec vel eros sed nulla sodales eleifend sit amet vel velit. Donec tempor tortor sit amet enim molestie hendrerit. Morbi ipsum ex, aliquet at aliquet vitae, egestas eu libero. Curabitur non mattis justo, sed volutpat lectus. Donec feugiat, ligula egestas aliquet accumsan, libero mauris pulvinar enim, ut commodo tellus lorem non urna. Lorem ipsum dolor sit amet, consectetur adipiscing elit. In hac habitasse platea dictumst. Etiam id sem nec sem ornare aliquam et et elit. In vulputate nisi ac scelerisque mollis. Cras et neque non mi eleifend finibus at a felis. Phasellus vel risus massa. Curabitur quis bibendum leo, eget imperdiet elit. Nam ac ante viverra mi ornare euismod ut sit amet erat. Donec dapibus dui nibh, vel gravida augue euismod eget. Etiam congue ultricies elit, id malesuada sem. Cras sollicitudin convallis dolor, tempor malesuada lectus facilisis non. Maecenas varius ullamcorper cursus. Fusce fermentum tincidunt purus eu egestas. Vivamus blandit posuere mauris, sed rhoncus orci bibendum sed. Fusce pulvinar suscipit libero id sodales. Vestibulum dapibus molestie quam quis consectetur. Ut dapibus, mauris eu maximus mollis, tortor arcu tincidunt est, ut bibendum metus mi id libero. Aliquam placerat eu turpis id hendrerit. Proin congue metus ligula, sed imperdiet nisl fermentum nec.',
    tracker: 'Bug',
    priority: 'Low',
    deadlineDate: '01-09-2024',
    progress: '0%',
    status: 'New',
    todoList: ['Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      'Sed feugiat dui a finibus sodales.',
      'Sed ac nisi vitae est ultrices sagittis quis et ex.',
      'Sed ut arcu non leo ultrices eleifend.',
      'Suspendisse sit amet mi ac mi consectetur accumsan.',
      'Sed laoreet diam a mauris molestie, a venenatis nisi eleifend',
      'Duis eget orci tincidunt, suscipit nisi nec, varius massa.',
      'Nulla sed risus suscipit, scelerisque ante eget, venenatis lectus.',
      'Pellentesque dignissim lorem non felis pharetra, ultrices facilisis sem faucibus.',
      'Aliquam pharetra erat non condimentum sodales.',
      'Maecenas blandit risus eget leo volutpat, sed interdum felis venenatis.',
      'Phasellus sodales lectus ac elit luctus, a mollis leo dictum.',
      'Praesent at libero eget tortor venenatis posuere ut quis sem.',
      'Donec sed metus molestie, imperdiet libero non, sagittis tellus.',
      'Donec vel sem vel purus cursus fringilla vitae eget leo.'
    ],),

];

